version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: marg_user
      POSTGRES_PASSWORD: marg_password
      POSTGRES_DB: marg_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
